cache_dir: cache
datasets:
- name: anachronisms
  split_seed: 42
  test_size: 5
  train_size: 5
# - name: sports_understanding
#   split_seed: 42
#   test_size: 100
#   train_size: 100
# - name: logical_deduction
#   split_seed: 42
#   test_size: 100
#   train_size: 100
# - name: social_chemistry
#   split_seed: 42
#   test_size: 100
#   train_size: 100

evaluate_confabulation: false
interactive: false
max_concurrent_models: 1
models:
# - backend: auto
#   batch_size: 1
#   device: auto
#   dtype: bfloat16
#   name: google/gemma-2-2b-it
# - backend: auto
#   batch_size: 1
#   device: auto
#   dtype: bfloat16
#   name: google/gemma-2-9b-it
# - backend: auto
#   batch_size: 1
#   device: auto
#   dtype: bfloat16
#   name: Qwen/Qwen2.5-3B-Instruct
- backend: auto
  batch_size: 1
  device: auto
  dtype: bfloat16
  name: Qwen/Qwen2.5-7B-Instruct
# - backend: auto
#   batch_size: 1
#   device: auto
#   dtype: bfloat16
#   name: microsoft/Phi-3-mini-4k-instruct
# - backend: auto
#   batch_size: 1
#   device: auto
#   dtype: bfloat16
#   name: Llama-2-7b-chat
save_generations: true
steering:
  alpha_range:
  - 2
  max_new_tokens: 200
  temperature: 0.7
  method: caa-single-layer
  max_gen: 2
use_cache: true
